---
# Service to expose frontend
apiVersion: v1
kind: Service
metadata:
  name: watson-conversation-app
  labels:
    app: watson-conversation-app
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: watson-conversation-app
    tier: frontend
---
# Application to deploy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watson-conversation-app
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: watson-conversation-app
        tier: frontend
    spec:
      containers:
      - name: watson-conversation-app
        image: docker.io/mdelder/watson-conversation-app:latest
        resources:
          requests:
            cpu: 500m
            memory: 100Mi
        env:
          - name: WORKSPACE_ID
            valueFrom:
              configMapKeyRef:
                name: car-dashboard-config
                key: workspace_id
          - name: CONVERSATION_SERVICE_CAR
            valueFrom:
              secretKeyRef:
                name: binding-conversation-service-car
                key: binding
