apiVersion: policy.mcm.ibm.com/v1alpha1
kind: Policy
metadata:
  name: watson-conversation-app-clusterimage-policy
  namespace: kube-system
  annotations:
    policy.mcm.ibm.com/standards: NIST,HIPAA
    policy.mcm.ibm.com/categories: SystemAndCommunicationsProtections,SystemAndInformationIntegrity
    policy.mcm.ibm.com/controls: MutationAdvisor,VA
spec:
  complianceType: musthave
  namespaces:
    exclude:
      - kube*
    include:
      - default
  remediationAction: enforce
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: securityenforcement.admission.cloud.ibm.com/v1beta1
        kind: ClusterImagePolicy
        metadata:
          name: watson-conversation-app-cluster-image-policy
        spec:
          repositories:
          - name: docker.io/mdelder/watson-conversation-app:*
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: multicloud-clusterimage-placement-binding
  namespace: kube-system
placementRef:
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
  name: production-clusters-placement
subjects:
- kind: Policy
  apiGroup: policy.mcm.ibm.com
  name: watson-conversation-app-clusterimage-policy
---
apiVersion: mcm.ibm.com/v1alpha1
kind: PlacementBinding
metadata:
  name: multicloud-clusterimage-dev-placement-binding
  namespace: kube-system
placementRef:
  kind: PlacementPolicy
  apiGroup: mcm.ibm.com
  name: dev-clusters-placement
subjects:
- kind: Policy
  apiGroup: policy.mcm.ibm.com
  name: watson-conversation-app-clusterimage-policy
